# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 09:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=200, verbose_name='\u54c1\u724c')),
                ('brand_first', models.CharField(max_length=200, verbose_name='\u54c1\u724c\u9996\u5b57\u6bcd')),
                ('car_name', models.CharField(max_length=200, verbose_name='\u8f66\u7cfb')),
                ('car_type', models.CharField(max_length=200, verbose_name='\u7c7b\u578b')),
                ('model_name', models.CharField(max_length=200, verbose_name='\u578b\u53f7')),
                ('url', models.CharField(max_length=200, verbose_name='\u91c7\u96c6\u5730\u5740')),
                ('shangpai_date', models.CharField(max_length=200, verbose_name='\u4e0a\u724c\u65f6\u95f4')),
                ('address', models.CharField(max_length=200, verbose_name='\u4e0a\u724c\u57ce\u5e02')),
                ('xingshi', models.CharField(max_length=200, verbose_name='\u884c\u9a76\u91cc\u7a0b(\u4e07\u516c\u91cc)')),
                ('price', models.CharField(max_length=200, verbose_name='\u6807\u4ef7')),
                ('price_new', models.CharField(max_length=200, verbose_name='\u65b0\u8f66\u6307\u5bfc\u4ef7')),
                ('website', models.CharField(choices=[('guzi', '\u74dc\u5b50\u7f51'), ('xin', '\u4f18\u4fe1')], max_length=200, verbose_name='\u6765\u6e90\u7f51\u7ad9')),
                ('guid', models.CharField(max_length=200, verbose_name='\u552f\u4e00\u7801')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shangpai_date', models.DateTimeField(max_length=200, verbose_name='\u4e0a\u724c\u65f6\u95f4')),
                ('xingshi', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='\u884c\u9a76\u91cc\u7a0b(\u4e07\u516c\u91cc)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='\u6807\u4ef7(\u4e07\u5143)')),
            ],
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=200, verbose_name='\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(max_length=200, verbose_name='\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='car',
            name='type',
            field=models.CharField(choices=[('two', '\u4e24\u53a2'), ('three', '\u4e09\u53a2'), ('sport', '\u8dd1\u8f66'), ('suv', 'SUV'), ('mpv', 'MPV'), ('pickup', '\u76ae\u5361'), ('van', '\u9762\u5305\u8f66'), ('other', '\u5176\u4ed6')], max_length=10, verbose_name='\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=200, verbose_name='\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='model',
            name='name',
            field=models.CharField(max_length=200, verbose_name='\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='model',
            name='price_new',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='\u65b0\u8f66\u6307\u5bfc\u4ef7(\u4e07\u5143)'),
        ),
        migrations.AlterField(
            model_name='province',
            name='name',
            field=models.CharField(max_length=200, verbose_name='\u540d\u79f0'),
        ),
        migrations.AddField(
            model_name='sale',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.City'),
        ),
        migrations.AddField(
            model_name='sale',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.Model'),
        ),
    ]
