# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='caiji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chengshi', models.CharField(max_length=200, verbose_name='城市')),
                ('qu', models.CharField(max_length=200, verbose_name='区')),
                ('pian', models.CharField(max_length=200, verbose_name='片')),
                ('xiaoqu', models.CharField(max_length=200, verbose_name='小区')),
                ('huxing', models.CharField(max_length=200, verbose_name='户型')),
                ('mianji', models.CharField(max_length=200, verbose_name='面积')),
                ('danjia', models.CharField(max_length=200, verbose_name='单价')),
                ('chaoxiang', models.CharField(max_length=200, verbose_name='朝向')),
                ('louceng', models.CharField(max_length=200, verbose_name='楼层')),
                ('zonglouceng', models.CharField(max_length=200, verbose_name='总楼层')),
                ('zhuangxiu', models.CharField(max_length=200, verbose_name='装修')),
                ('xuexiao', models.CharField(max_length=200, verbose_name='学校')),
                ('niandai', models.CharField(max_length=200, verbose_name='建筑年代')),
                ('dianti', models.CharField(max_length=200, verbose_name='有无电梯')),
                ('chanquan', models.CharField(max_length=200, verbose_name='产权性质')),
                ('guapai', models.CharField(max_length=200, verbose_name='挂牌时间')),
                ('gengxin', models.CharField(max_length=200, verbose_name='最后更新')),
                ('junjia', models.CharField(max_length=200, verbose_name='参考均价')),
                ('leixing', models.CharField(max_length=200, verbose_name='物业类型')),
                ('wuyefei', models.CharField(max_length=200, verbose_name='物业费用')),
                ('jianzhu', models.CharField(max_length=200, verbose_name='建筑类型')),
                ('nianxian', models.CharField(max_length=200, verbose_name='产权年限')),
                ('lvhua', models.CharField(max_length=200, verbose_name='绿化率')),
                ('rongji', models.CharField(max_length=200, verbose_name='容积率')),
                ('fenliu', models.CharField(max_length=200, verbose_name='人车分流')),
                ('loudong', models.CharField(max_length=200, verbose_name='总楼栋数')),
                ('hushu', models.CharField(max_length=200, verbose_name='总户数')),
                ('laiyuan', models.CharField(max_length=200, verbose_name='来源')),
                ('zhiwen', models.CharField(max_length=200, verbose_name='数据指纹')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('url', models.CharField(max_length=200, verbose_name='采集地址')),
            ],
        ),
    ]
