# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-05 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
            ],
        ),
        migrations.CreateModel(
            name='Fangwu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mianji', models.FloatField(verbose_name='面积')),
                ('danjia', models.FloatField(verbose_name='单价')),
                ('chaoxiang', models.IntegerField(choices=[(1, '东'), (2, '南'), (3, '西'), (4, '北'), (5, '东南'), (6, '西南'), (7, '西北'), (8, '东北'), (9, '南北'), (10, '东西')], verbose_name='朝向')),
                ('louceng', models.IntegerField(choices=[(1, '底层'), (2, '低层'), (3, '中层'), (4, '高层'), (5, '顶层')], verbose_name='楼层')),
                ('zonglouceng', models.IntegerField(verbose_name='总楼层')),
                ('zhuangxiu', models.IntegerField(choices=[(1, '毛坯'), (2, '简装修'), (3, '中装修'), (4, '精装修'), (5, '豪华装修')], verbose_name='装修')),
                ('niandai', models.IntegerField(verbose_name='建筑年代')),
                ('dianti', models.IntegerField(choices=[(1, '有'), (2, '无')], verbose_name='电梯')),
                ('chanquan', models.IntegerField(choices=[(1, '个人产权'), (2, '商品房')], verbose_name='产权')),
                ('guapai', models.DateField(verbose_name='挂牌日期')),
                ('gengxin', models.DateField(verbose_name='更新日期')),
                ('leixing', models.IntegerField(choices=[(1, '住宅'), (2, '别墅')], verbose_name='物业类型')),
                ('wuyefei', models.FloatField(verbose_name='物业费')),
                ('jianzhu', models.IntegerField(choices=[(1, '塔楼'), (2, '板楼'), (3, '板塔结合'), (4, '联排'), (5, '叠拼'), (6, '双拼'), (7, '独栋')], verbose_name='建筑类型')),
                ('nianxian', models.IntegerField(verbose_name='产权年限')),
                ('lvhua', models.FloatField(verbose_name='绿化率')),
                ('rongji', models.FloatField(verbose_name='容积率')),
                ('fenliu', models.IntegerField(choices=[(1, '有'), (2, '无')], verbose_name='人车分流')),
                ('loudong', models.IntegerField(verbose_name='总楼栋数')),
                ('hushu', models.IntegerField(verbose_name='总户数')),
                ('zhiwen', models.CharField(max_length=200, verbose_name='数据指纹')),
            ],
        ),
        migrations.CreateModel(
            name='Huxing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('shi', models.IntegerField(verbose_name='室')),
                ('ting', models.IntegerField(verbose_name='厅')),
                ('wei', models.IntegerField(verbose_name='卫')),
            ],
        ),
        migrations.CreateModel(
            name='Pian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
            ],
        ),
        migrations.CreateModel(
            name='Qu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.City')),
            ],
        ),
        migrations.CreateModel(
            name='Xiaoqu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('pian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.Pian')),
            ],
        ),
        migrations.CreateModel(
            name='Xuexiao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.City')),
            ],
        ),
        migrations.RenameField(
            model_name='caiji',
            old_name='createTime',
            new_name='create_date',
        ),
        migrations.AddField(
            model_name='pian',
            name='qu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.Qu'),
        ),
        migrations.AddField(
            model_name='fangwu',
            name='huxing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.Huxing'),
        ),
        migrations.AddField(
            model_name='fangwu',
            name='xiaoqu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.Xiaoqu'),
        ),
        migrations.AddField(
            model_name='fangwu',
            name='xuexiao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.Xuexiao'),
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.Province'),
        ),
    ]
