# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 08:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_auto_20171108_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='fangwu',
            name='city',
            field=models.ForeignKey(default=360, on_delete=django.db.models.deletion.CASCADE, to='house.City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fangwu',
            name='pian',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='house.Pian'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fangwu',
            name='qu',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='house.Qu'),
            preserve_default=False,
        ),
    ]
