# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 10:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0004_auto_20171108_0805'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chanquan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('danjia', models.FloatField(null=True, verbose_name='单价')),
            ],
        ),
        migrations.CreateModel(
            name='Chaoxiang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('danjia', models.FloatField(null=True, verbose_name='单价')),
            ],
        ),
        migrations.CreateModel(
            name='City_chanquan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('danjia', models.FloatField(null=True, verbose_name='单价')),
                ('chanquan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.Chanquan')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.City')),
            ],
        ),
        migrations.CreateModel(
            name='City_chaoxiang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('danjia', models.FloatField(null=True, verbose_name='单价')),
                ('chaoxiang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.Chaoxiang')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.City')),
            ],
        ),
        migrations.CreateModel(
            name='City_huxing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('danjia', models.FloatField(null=True, verbose_name='单价')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.City')),
                ('huxing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.Huxing')),
            ],
        ),
        migrations.CreateModel(
            name='City_jianzhu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('danjia', models.FloatField(null=True, verbose_name='单价')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.City')),
            ],
        ),
        migrations.CreateModel(
            name='City_louceng',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('danjia', models.FloatField(null=True, verbose_name='单价')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.City')),
            ],
        ),
        migrations.CreateModel(
            name='Jianzhu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('danjia', models.FloatField(null=True, verbose_name='单价')),
            ],
        ),
        migrations.CreateModel(
            name='Louceng',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('danjia', models.FloatField(null=True, verbose_name='单价')),
            ],
        ),
        migrations.AddField(
            model_name='city_louceng',
            name='louceng',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.Louceng'),
        ),
        migrations.AddField(
            model_name='city_jianzhu',
            name='jianzhu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.Jianzhu'),
        ),
    ]
