# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0005_auto_20171108_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fangwu',
            name='dianti',
        ),
        migrations.RemoveField(
            model_name='fangwu',
            name='fenliu',
        ),
        migrations.RemoveField(
            model_name='fangwu',
            name='hushu',
        ),
        migrations.RemoveField(
            model_name='fangwu',
            name='leixing',
        ),
        migrations.RemoveField(
            model_name='fangwu',
            name='loudong',
        ),
        migrations.RemoveField(
            model_name='fangwu',
            name='lvhua',
        ),
        migrations.RemoveField(
            model_name='fangwu',
            name='nianxian',
        ),
        migrations.RemoveField(
            model_name='fangwu',
            name='rongji',
        ),
        migrations.RemoveField(
            model_name='fangwu',
            name='wuyefei',
        ),
        migrations.RemoveField(
            model_name='fangwu',
            name='zhuangxiu',
        ),
        migrations.RemoveField(
            model_name='fangwu',
            name='zonglouceng',
        ),
        migrations.AddField(
            model_name='louceng',
            name='lou',
            field=models.CharField(default=1, max_length=200, verbose_name='所在楼层'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='louceng',
            name='max',
            field=models.IntegerField(default=1, verbose_name='最大总楼层'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='louceng',
            name='min',
            field=models.IntegerField(default=1, verbose_name='最小总楼层'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fangwu',
            name='chanquan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.Chanquan'),
        ),
        migrations.AlterField(
            model_name='fangwu',
            name='chaoxiang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.Chaoxiang'),
        ),
        migrations.AlterField(
            model_name='fangwu',
            name='jianzhu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.Jianzhu'),
        ),
        migrations.AlterField(
            model_name='fangwu',
            name='louceng',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.Louceng'),
        ),
    ]
