# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 13:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0006_auto_20171108_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fangwu',
            name='xuexiao',
        ),
    ]
