# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0007_remove_fangwu_xuexiao'),
    ]

    operations = [
        migrations.AddField(
            model_name='caiji',
            name='jianzhujiegou',
            field=models.CharField(default='', max_length=200, verbose_name='建筑结构'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caiji',
            name='jianzhuleibie',
            field=models.CharField(default='', max_length=200, verbose_name='建筑类别'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caiji',
            name='jianzhuxingshi',
            field=models.CharField(default='', max_length=200, verbose_name='建筑形式'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caiji',
            name='zhuzhaileibie',
            field=models.CharField(default='', max_length=200, verbose_name='住宅类别'),
            preserve_default=False,
        ),
    ]
