# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0009_caiji_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caiji',
            name='status',
            field=models.CharField(max_length=200, verbose_name='状态'),
        ),
    ]
